apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    app.kubernetes.io/managed-by: opsera
    opsera.io/tenant: opsera
    opsera.io/app: {{ .Values.appName }}
    opsera.io/env: dev
